# Generated by Django 5.2 on 2025-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_talaba_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='qaytarilgan',
            field=models.BooleanField(null=True),
        ),
    ]
